spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ordb?serverTimezone=UTC
    username: root
    password: 11111111
  jpa:
    hibernate:
      ddl-auto: update
  jackson:
    property-naming-strategy: SNAKE_CASE

jwt:
  header: Authorization
  prefix : Bearer
  secret: orjwtsecret
  access-exp: 3600

cloud:
  aws:
    s3:
      bucket: ${S3_BUCKET}
      url: ${S3_URL}
    credentials:
      access-key: ${S3_ACCESS}
      secret-key: ${S3_SECRET}
    region:
      static: ${S3_REGION}
    stack:
      auto: false

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
